services:
  postgres:
    image: postgres:latest
    container_name: black-lotus-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: black-lotus-server
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
      SERVER_PORT: ${SERVER_PORT}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_DB_HOST: ${TEST_DB_HOST}
      TEST_DB_PORT: ${TEST_DB_PORT}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      ENV: development
      FRONTEND_URL: http://localhost:3000
    ports:
      - '${SERVER_PORT}:8080'
    depends_on:
      - postgres
    networks:
      - app-network
    # Add tmpfs for build cache
    tmpfs:
      - /tmp/go-cache:exec
      - /tmp/go-mod-cache:exec
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: black-lotus-client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:${SERVER_PORT}
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  postgres-data:
